sudo: required

langauge: python

services:
  - docker

before_install:
- docker pull tp33/django
- docker pull mysql:5.7.14
- mkdir db
- docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/db:/var/lib/mysql mysql:5.7.14
- docker ps -a