web:
  image: tp33/django
  external_links:
    - mysql-test:db
  container_name: web_container
  volumes:
    - ./app:/app
  command: >
          bash -c "cd sampleProject/ &&
                  python manage.py migrate &&
                  mod_wsgi-express start-server --working-directory /app/sampleProject/ /app/sampleProject/sampleProject/wsgi.py"